stages:
  - deploy

deploy_research_test:
  stage: deploy
  script:
    - docker compose up -d --build
  environment:
    name: research test
    url: https://cada11y-test.cs.washington.edu
  tags:
    - lab-docker-test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy_research_prod:
  stage: deploy
  script:
    - docker compose up -d --build
  environment:
    name: research prod
    url: https://cada11y.cs.washington.edu
  tags:
    - lab-docker-prod
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v/'
